config/routes.rb
Rails.application.routes.draw do
  devise_for :nodriza_admins
  resources :forms
  authenticated :nodriza_admin do
    root 'forms#index_admin'
  end

  unauthenticated :nodriza_admin do
    devise_scope :nodriza_admin do
      root 'forms#index', as: :unregistered_root
    end
  end

end

app/models/form.rb
class Form < ActiveRecord::Base
	validates_presence_of :nombre, message: "Tu nombre es requerido para la inscripción"
	validates :nombre, length: { minimum: 5, too_short: "debe tener al menos %{count} caracteres" }
	validates_presence_of :email, length: {minimum:4}, message: "Tu correo es requerido para la inscripción"
	validates_uniqueness_of :email, message: "Este correo ya fue registrado"
	validates_presence_of :telefono, message: "Este campo es requerido"

end

app/models/nodriza_admin.rb
class NodrizaAdmin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
    @form = Form.new
  end

  def index_admin
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:nombre, :email, :telefono)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="form_nombre">Nombre Completo</label><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<%= form_for(@form, remote: true, html: {id: "formulario"}) do |f| %>

  <div id="form-container">
    <div class="input-field">
      <%= f.label :nombre, 'Nombre y Apellido' %> <br>
      <%= f.text_field :nombre, id: 'form_nombre' %>
      <div id="error-nombre" class="error"></div>
    </div>
    <div class="input-field">
      <%= f.label :email %><br>
      <%= f.email_field :email, id: 'form_email' %>
      <div id="error-email" class="error"></div>
    </div>
    <div class="input-field">
      <%= f.label :telefono, "Teléfono" %><br>
      <%= f.text_field :telefono %>
      <div id="error-telefono" class="error"></div>
    </div>
    <div class="submit-container">
      <%= f.submit 'registrate', :class => 'waves-effect waves-light btn submit red'%>
    </div>    
  </div>
  <div id="exito" class="exito opacity">
    <div class='success light-green darken-2'>
      <div class="icon-preview col s6 m3 done">
        <i class="material-icons dp48">thumb_up</i>
      </div>
      <p>
        Inscripción exitosa, te esperamos.
      </p>
    </div>
    <a href='https://www.toolmania.cl' class="waves-effect waves-light btn toolmania amber darken-1">Ir a toolmania</a>
    <div class='powered'> 
      <p>powered by nodriza </p>
      <%= image_tag ('nodriza.png') %>
    </div>
  </div>
<% end %>

app/views/forms/index_admin.html.erb
<div class="menu">
	<%= link_to "cerrar sesión", destroy_nodriza_admin_session_path, method: :delete, :class => 'waves-effect waves-light btn  grey darken-3'%>
</div>
<h1 class="titulo color-naranjo">Registros</h1>

<table class="tabla highlight">
  <thead>
    <tr>
      <th data-field="id">id</th>
      <th data-field="nombre">Nombre</th>
      <th data-field="email">email</th>
      <th data-field="telefono">telefono</th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
      	<td><%= form.id %></td>
        <td><%= form.nombre %></td>
        <td><%= form.email %></td>
        <td><%= form.telefono %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @form.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @form.email %>
</p>



<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clinica Bosch</title>
  <meta name="description" content="Formluraio de inscripción para evento makita-day organizado por toolmania">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	
</head>
<body>
	<header>
		<figure>
			<%= image_tag ("header.png") %>
		</figure>

		<div class="introduccion">
			<p>
				Te invitamos a participar de nuestro primer ciclo de <span>"CLÍNICAS DE HERRAMIENTAS"</span>.
			</p>
			<ul>
				<li><i class="small material-icons color-naranjo">done</i>Partiremos con la linea de medición de nuestros amigos de Boch.</li>
				<li><i class="small material-icons color-naranjo">done</i>Esta actividad se desarrollará en vivo, con los especialistas en el tema.</li>
				<li><i class="small material-icons color-naranjo">done</i>Responderemos todas sus dudas en relación a los productos de medición Bosch, mostrar sus particularidades y bondades.</li>
			</ul>
		</div>

	</header>
	<div class="common">
		<p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>
	</div>

	<%= yield %>
	<div class="header-bottom">
		<p>by</p>
		<figure>
			<%= image_tag ("toolmania.png") %>
		</figure>
		<figure>
			<%= image_tag ("bosch.png") %>
		</figure>
	</div>

</body>
</html>